[project]
channels = ["conda-forge", "dglteam/label/th24_cu124"]
description = "Add a short description here"
name = "cgcnn_deepchem"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
crossval = "python crossval_main.py"

[system-requirements]
cuda = "12.4"


[dependencies]
pytorch-gpu = ">=2.5.1,<3"
python = "*"
deepchem = ">=2.8.0,<3"
tqdm = ">=4.67.1,<5"
ipykernel = ">=6.29.5,<7"
rdkit = ">=2024.9.3,<2025"
pymatgen = ">=2024.8.9,<2025"
dgl = { version = ">=2.4.0.th24.cu124,<3", channel = "dglteam/label/th24_cu124" }
